# Generated by Django 5.2.17 on 2026-09-05 11:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.core.files.base import ContentFile
from django.db import migrations, models

import tracks.models


def archive_existing_tracks(apps, schema_editor):
    Track = apps.get_model("tracks", "Track")
    alias = schema_editor.connection.alias
    storage = Track._meta.get_field("original_gpx_file").storage
    for track in Track.objects.using(alias).filter(original_gpx_file="").iterator():
        with track.gpx_file.open("rb") as source:
            content = source.read()
        # A deterministic destination allows retry after a database rollback.
        name = f"originals/migrated/{track.public_id.hex}.gpx"
        if storage.exists(name):
            with storage.open(name, "rb") as archived:
                if archived.read() != content:
                    raise RuntimeError(f"Archive differs from track {track.pk}; refusing overwrite")
        else:
            name = storage.save(name, ContentFile(content))
        Track.objects.using(alias).filter(pk=track.pk).update(original_gpx_file=name)


class Migration(migrations.Migration):
    dependencies = [
        ("tracks", "0004_track_geometry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="название")),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="создана")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="изменена")),
            ],
            options={
                "verbose_name": "группа треков",
                "verbose_name_plural": "группы треков",
                "ordering": ["-updated_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="TrackGroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0, verbose_name="порядок")),
            ],
            options={
                "verbose_name": "участие трека в группе",
                "verbose_name_plural": "состав групп",
                "ordering": ["position", "pk"],
            },
        ),
        migrations.AddField(
            model_name="track",
            name="original_gpx_file",
            field=models.FileField(
                default="",
                editable=False,
                upload_to=tracks.models.original_gpx_path,
                verbose_name="архивный GPX",
            ),
        ),
        migrations.RunPython(archive_existing_tracks, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="track",
            constraint=models.CheckConstraint(
                condition=models.Q(("original_gpx_file", ""), _negated=True),
                name="track_has_original_gpx",
            ),
        ),
        migrations.AddField(
            model_name="trackgroup",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="track_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="владелец",
            ),
        ),
        migrations.AddField(
            model_name="trackgroupmembership",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="tracks.trackgroup",
            ),
        ),
        migrations.AddField(
            model_name="trackgroupmembership",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_memberships",
                to="tracks.track",
            ),
        ),
        migrations.AddField(
            model_name="trackgroup",
            name="tracks",
            field=models.ManyToManyField(
                related_name="groups", through="tracks.TrackGroupMembership", to="tracks.track"
            ),
        ),
        migrations.AddIndex(
            model_name="trackgroupmembership",
            index=models.Index(fields=["group", "position"], name="tracks_trac_group_i_557cd4_idx"),
        ),
        migrations.AddConstraint(
            model_name="trackgroupmembership",
            constraint=models.UniqueConstraint(
                fields=("group", "track"), name="unique_group_track"
            ),
        ),
        migrations.AddConstraint(
            model_name="trackgroupmembership",
            constraint=models.UniqueConstraint(fields=("track",), name="one_group_per_track"),
        ),
    ]
