# Generated by Django 5.2.17 on 2026-09-05 14:33

from django.db import migrations, models


def populate_waypoints(apps, schema_editor):
    from tracks.services import parse_gpx

    Track = apps.get_model("tracks", "Track")
    for track in Track.objects.using(schema_editor.connection.alias).iterator():
        with track.gpx_file.open("rb") as source:
            parsed = parse_gpx(source.read())
        Track.objects.using(schema_editor.connection.alias).filter(pk=track.pk).update(
            geojson=parsed.geojson,
            waypoints_count=parsed.waypoints_count,
            min_latitude=parsed.min_latitude,
            max_latitude=parsed.max_latitude,
            min_longitude=parsed.min_longitude,
            max_longitude=parsed.max_longitude,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("tracks", "0005_trackgroup_trackgroupmembership_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="waypoints_count",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="путевых точек"
            ),
        ),
        migrations.RunPython(populate_waypoints, migrations.RunPython.noop),
    ]
